[package]
name = "radiko-rs"
version = "0.1.0"
edition = "2024"

[lib]
name = "radiko_rs"

[dependencies]
anyhow = "1.0.98"
base64 = "0.22.1"
regex = "1.11.1"
reqwest = "0.12.20"
tokio = { version = "1.45.1", features = ["full"] }
