name: Scheduled Tests

on:
  schedule:
    - cron: '0 * * * *'  # 1時間毎
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: cargo test on docker
      run: |
        docker pull ghcr.io/t9a-dev/run-cargo-test:latest
        # Radiko APIに変更があるとテストが失敗する（Radiko API変更検知）
        docker run -e mail=${{ secrets.RADIKO_MAIL }} -e pass=${{ secrets.RADIKO_PASS}} --rm ghcr.io/t9a-dev/run-cargo-test:latest
    
    - name: Create issue on failure
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        title: failed scheduled action
        token: ${{ secrets.CREATE_ISSUE_TOKEN }}