name: Scheduled Tests

on:
  schedule:
    - cron: '*/30 * * * *'  # Run every 30 minutes
  workflow_dispatch:  # Allow manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: addnab/docker-run-action@v3
      with:
        registry: gcr.io
        image: t9a-dev/run-cargo-test:latest
        run: echo "run cargo-test"
    
    - name: Create issue on failure
      if: ${{ failure() }}
      uses: dacbd/create-issue-action@main
      with:
        title: failed scheduled action
        token: ${{ secrets.CREATE_ISSUE_TOKEN }}