# .github/workflows/docker-publish.yml
name: docker-publish

on:
  push:
    branches: [ master ]
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write         # GHCR に push するため
  id-token: write         # OIDC 署名に必要

env:
  IMAGE_NAME: ghcr.io/t9a-dev/run-cargo-test:latest

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
            ref: master
            fetch-depth: 0

      - uses: docker/setup-buildx-action@v3

      # GHCR にログイン（GITHUB_TOKENでOK）
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # ビルド & プッシュ（PR時はpushしない）
      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.ci
          push: true
          # platforms: linux/amd64,linux/arm64  # マルチアーキにするならコメント解除
          tags: ${{ env.IMAGE_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max